site_name: QuantEcon.jl
site_description: QuantEcon.jl Quantitative economics in Julia
site_author: Spencer Lyon
repo_name: GitHub
site_favicon: favicon.ico
docs_dir: 'docs'
site_dir: 'site'
repo_url: https://github.com/QuantEcon/QuantEcon.jl/

pages:
- Home: 'index.md'
- Overview: 'api/index.md'
- API Docs:
  - QuantEcon: 'api/QuantEcon.md'
  - Models: 'api/QuantEcon.Models.md'
